-- MySQL Script generated by MySQL Workbench
-- Wed Jan 20 15:22:49 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SchoolDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SchoolDatabase` ;

-- -----------------------------------------------------
-- Schema SchoolDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SchoolDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SchoolDatabase` ;

-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Teacher` (
  `Teacher_ID` INT NOT NULL AUTO_INCREMENT,
  `Teacher_Title` VARCHAR(45) NOT NULL,
  `Teacher_Fname` VARCHAR(45) NOT NULL,
  `Teacher_Lname` VARCHAR(45) NOT NULL,
  `Teacher_Email` VARCHAR(45) NOT NULL,
  `Teacher_Mobile_Number` VARCHAR(45) NULL,
  `Teacher_Username` VARCHAR(45) NOT NULL,
  `Teacher_Password` VARCHAR(300) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Teacher_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Parent` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Parent` (
  `Parent_ID` INT NOT NULL AUTO_INCREMENT,
  `Parent_Title` VARCHAR(45) NOT NULL,
  `Parent_Fname` VARCHAR(45) NOT NULL,
  `Parent_Lname` VARCHAR(45) NOT NULL,
  `Parent_Email` VARCHAR(45) NOT NULL,
  `Parent_Mobile_Number` VARCHAR(15) NULL,
  `Parent_Home_Number` VARCHAR(15) NULL,
  `Parent_Address` VARCHAR(100) NULL,
  `Parent_Username` VARCHAR(45) NOT NULL,
  `Parent_Password` VARCHAR(300) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Parent_ID`),
  UNIQUE INDEX `Parent_ID_UNIQUE` (`Parent_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Student` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Student` (
  `Student_ID` INT NOT NULL AUTO_INCREMENT,
  `Student_Title` VARCHAR(45) NOT NULL,
  `Student_Fname` VARCHAR(45) NOT NULL,
  `Student_Lname` VARCHAR(45) NOT NULL,
  `Student_Email` VARCHAR(45) NULL,
  `Student_Year` INT NULL,
  `Student_Username` VARCHAR(45) NULL,
  `Student_Password` VARCHAR(300) NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Student_ID`),
  UNIQUE INDEX `Student_ID_UNIQUE` (`Student_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Subject` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Subject` (
  `Subject_ID` INT NOT NULL AUTO_INCREMENT,
  `Subject_Name` VARCHAR(45) NOT NULL,
  `Subject_Description` VARCHAR(45) NULL,
  PRIMARY KEY (`Subject_ID`),
  UNIQUE INDEX `Subject_ID_UNIQUE` (`Subject_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Room` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Room` (
  `Room_ID` INT NOT NULL AUTO_INCREMENT,
  `Room_Name` VARCHAR(45) NOT NULL,
  `Rom_Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Room_ID`),
  UNIQUE INDEX `Room_ID_UNIQUE` (`Room_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Class` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Class` (
  `Class_ID` INT NOT NULL AUTO_INCREMENT,
  `Class_Level` VARCHAR(45) NOT NULL,
  `Class_Start_Timestamp` TIMESTAMP NOT NULL,
  `Class_End_Timestamp` TIMESTAMP NOT NULL,
  `Subject_ID` INT NOT NULL,
  `Room_ID` INT NOT NULL,
  `Teacher_ID` INT NOT NULL,
  PRIMARY KEY (`Class_ID`, `Subject_ID`, `Room_ID`, `Teacher_ID`),
  INDEX `fk_Class_Subject1_idx` (`Subject_ID` ASC),
  INDEX `fk_Class_Room1_idx` (`Room_ID` ASC),
  INDEX `fk_Class_Teacher1_idx` (`Teacher_ID` ASC),
  UNIQUE INDEX `Class_ID_UNIQUE` (`Class_ID` ASC),
  CONSTRAINT `fk_Class_Subject1`
    FOREIGN KEY (`Subject_ID`)
    REFERENCES `SchoolDatabase`.`Subject` (`Subject_ID`)
    ON DELETE NO ACTION,
  CONSTRAINT `fk_Class_Room1`
    FOREIGN KEY (`Room_ID`)
    REFERENCES `SchoolDatabase`.`Room` (`Room_ID`)
    ON DELETE NO ACTION,
  CONSTRAINT `fk_Class_Teacher1`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `SchoolDatabase`.`Teacher` (`Teacher_ID`)
    ON DELETE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Admin` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Admin` (
  `Admin_ID` INT NOT NULL AUTO_INCREMENT,
  `Admin_Title` VARCHAR(45) NOT NULL,
  `Admin_Fname` VARCHAR(45) NOT NULL,
  `Admin_Lname` VARCHAR(45) NOT NULL,
  `Admin_Email` VARCHAR(45) NOT NULL,
  `Admin_Privledge_Level` VARCHAR(45) NULL,
  `Admin_Username` VARCHAR(45) NOT NULL,
  `Admin_Password` VARCHAR(300) NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Admin_ID`),
  UNIQUE INDEX `Admin_ID_UNIQUE` (`Admin_ID` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Student_has_Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Student_has_Class` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Student_has_Class` (
  `Student_ID` INT NOT NULL,
  `Class_ID` INT NOT NULL,
  PRIMARY KEY (`Student_ID`, `Class_ID`),
  INDEX `fk_Student_has_Class_Class1_idx` (`Class_ID` ASC),
  INDEX `fk_Student_has_Class_Student_idx` (`Student_ID` ASC),
  CONSTRAINT `fk_Student_has_Class_Student`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `SchoolDatabase`.`Student` (`Student_ID`)
    ON DELETE NO ACTION,
  CONSTRAINT `fk_Student_has_Class_Class1`
    FOREIGN KEY (`Class_ID`)
    REFERENCES `SchoolDatabase`.`Class` (`Class_ID`)
    ON DELETE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Student_has_Parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Student_has_Parent` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Student_has_Parent` (
  `Student_Student_ID` INT NOT NULL,
  `Parent_Parent_ID` INT NOT NULL,
  PRIMARY KEY (`Student_Student_ID`, `Parent_Parent_ID`),
  INDEX `fk_Student_has_Parent_Parent1_idx` (`Parent_Parent_ID` ASC),
  INDEX `fk_Student_has_Parent_Student1_idx` (`Student_Student_ID` ASC),
  CONSTRAINT `fk_Student_has_Parent_Student1`
    FOREIGN KEY (`Student_Student_ID`)
    REFERENCES `SchoolDatabase`.`Student` (`Student_ID`)
    ON DELETE NO ACTION,
  CONSTRAINT `fk_Student_has_Parent_Parent1`
    FOREIGN KEY (`Parent_Parent_ID`)
    REFERENCES `SchoolDatabase`.`Parent` (`Parent_ID`)
    ON DELETE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SchoolDatabase`.`Attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolDatabase`.`Attendance` ;

CREATE TABLE IF NOT EXISTS `SchoolDatabase`.`Attendance` (
  `Attendance_ID` INT NOT NULL AUTO_INCREMENT,
  `Attendance_Status` VARCHAR(45) NOT NULL,
  `Attendance_Remarks` VARCHAR(45) NULL,
  `Class_ID` INT NOT NULL,
  `Student_ID` INT NOT NULL,
  PRIMARY KEY (`Attendance_ID`, `Class_ID`, `Student_ID`),
  INDEX `fk_Attendance_Class1_idx` (`Class_ID` ASC),
  INDEX `fk_Attendance_Student1_idx` (`Student_ID` ASC),
  UNIQUE INDEX `Attendance_ID_UNIQUE` (`Attendance_ID` ASC),
  CONSTRAINT `fk_Attendance_Class1`
    FOREIGN KEY (`Class_ID`)
    REFERENCES `SchoolDatabase`.`Class` (`Class_ID`)
    ON DELETE NO ACTION,
  CONSTRAINT `fk_Attendance_Student1`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `SchoolDatabase`.`Student` (`Student_ID`)
    ON DELETE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-------------------------- INSERT Statements---------------------------------------------
--Teacher
INSERT INTO Teacher (Teacher_Title, Teacher_Fname, Teacher_Lname, Teacher_Email, Teacher_Mobile_Number, Teacher_Username, Teacher_Password, Role)
VALUES ('Mr', 'Robert','Sonny','Robert.Sonny@hotmail.com','07981691495','RobertSonny', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Teacher');
INSERT INTO Teacher (Teacher_Title, Teacher_Fname, Teacher_Lname, Teacher_Email, Teacher_Mobile_Number, Teacher_Username, Teacher_Password, Role)
VALUES ('Mrs', 'Rachel','Green','Rachel.Green@hotmail.com','07981691795','RachelGreen', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Teacher');
INSERT INTO Teacher (Teacher_Title, Teacher_Fname, Teacher_Lname, Teacher_Email, Teacher_Mobile_Number, Teacher_Username, Teacher_Password, Role)
VALUES ('Mrs', 'Erik','Nagy','Erik.Nagy@hotmail.com','07981391795','ErikNagy', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Teacher');
--Parent
INSERT INTO Parent (Parent_Title, Parent_Fname, Parent_Lname, Parent_Email, Parent_Mobile_Number, Parent_Home_Number, Parent_Address, Parent_Username, Parent_Password, Role)
VALUES ('Mr', 'Richard', 'Love', 'Richad.Love@gmail.com', '0782637463', '01634237485', 'ME89E4', 'RichardLove', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Parent');
INSERT INTO Parent (Parent_Title, Parent_Fname, Parent_Lname, Parent_Email, Parent_Mobile_Number, Parent_Home_Number, Parent_Address, Parent_Username, Parent_Password, Role)
VALUES ('Mrs', 'Belinda', 'Love', 'Belinda.Love@gmail.com', '0782237463', '01634237485', 'ME89E4', 'BelindaLove', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Parent');
INSERT INTO Parent (Parent_Title, Parent_Fname, Parent_Lname, Parent_Email, Parent_Mobile_Number, Parent_Home_Number, Parent_Address, Parent_Username, Parent_Password, Role)
VALUES ('Mr', 'Jason', 'King', 'Jason.King@gmail.com', '0782637463', '01634297485', 'ME59E4', 'JasonKing', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Parent');
--Student
INSERT INTO Student (Student_Title, Student_Fname, Student_Lname, Student_Email, Student_Year, Student_Username, Student_Password, Role)
VALUES ('Mr', 'Nick', 'Liffen', 'Nick.liffen@hotmail.com', '8', 'NickLiffen', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Student');
INSERT INTO Student (Student_Title, Student_Fname, Student_Lname, Student_Email, Student_Year, Student_Username, Student_Password, Role)
VALUES ('Mrs', 'Caris', 'Love', 'Caris.Love@hotmail.com', '9', 'CarisLove', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Student');
INSERT INTO Student (Student_Title, Student_Fname, Student_Lname, Student_Email, Student_Year, Student_Username, Student_Password, Role)
VALUES ('Mrs', 'Katie', 'King', 'Katie.King@hotmail.com', '10', 'KatieKing', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Student');
--Subject
INSERT INTO Subject (Subject_Name, Subject_Description)
VALUES ('English', 'English Language and Litriture');
INSERT INTO Subject (Subject_Name, Subject_Description)
VALUES ('Maths', 'Normal Mathmatics');
INSERT INTO Subject (Subject_Name, Subject_Description)
VALUES ('History', 'Histroy about the Normans');
--Room
INSERT INTO Room (Room_Name, Rom_Description)
VALUES ('3.0.1', 'Burnaby Building');
INSERT INTO Room (Room_Name, Rom_Description)
VALUES ('1.0.4', 'Richmond Building');
INSERT INTO Room (Room_Name, Rom_Description)
VALUES ('8.0.2', 'Portland Building');
--Class
INSERT INTO Class (Class_Level, Class_Start_Timestamp, Class_End_Timestamp, Subject_ID, Room_ID, Teacher_ID)
VALUES ('7', '2016-01-27 08:00:00', '2016-01-27 09:00:00', '1', '2', '1');
INSERT INTO Class (Class_Level, Class_Start_Timestamp, Class_End_Timestamp, Subject_ID, Room_ID, Teacher_ID)
VALUES ('11', '2016-01-27 09:00:00', '2016-01-27 10:00:00', '2', '1', '2');
INSERT INTO Class (Class_Level, Class_Start_Timestamp, Class_End_Timestamp, Subject_ID, Room_ID, Teacher_ID)
VALUES ('9', '2016-01-27 10:00:00', '2016-01-27 11:00:00', '3', '3', '3');
--Admin
INSERT INTO Admin (Admin_Title, Admin_Fname, Admin_Lname, Admin_Email, Admin_Privledge_Level, Admin_Username, Admin_Password, Role)
VALUES ('Mr', 'Andrew', 'Stockdale', 'Andrew.Stockdale@hotmail.com', '1', 'AndrewStockdale', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Admin');
INSERT INTO Admin (Admin_Title, Admin_Fname, Admin_Lname, Admin_Email, Admin_Privledge_Level, Admin_Username, Admin_Password, Role)
VALUES ('Mrs', 'Rachel', 'Bodkin', 'Rachel.Bodkin@hotmail.com', '2', 'RachelBodkin', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Admin');
INSERT INTO Admin (Admin_Title, Admin_Fname, Admin_Lname, Admin_Email, Admin_Privledge_Level, Admin_Username, Admin_Password, Role)
VALUES ('Mrs', 'Sophie', 'Clarke', 'Sophie.Clarke@hotmail.com', '1', 'SophieClarke', '$2a$08$gnA71gTP.S2.DW51s0dpG.G1uBlN6sKM4anblcvFAZoWUrNLnaaWe', 'Admin');
--Student_has_Class
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('1', '1');
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('2', '1');
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('3', '1');
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('1', '2');
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('2', '2');
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('3', '2');
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('1', '3');
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('2', '3');
INSERT INTO Student_has_Class (Student_ID, Class_ID)
VALUES ('3', '3');
--Student_has_Parent
INSERT INTO Student_has_Parent (Student_Student_ID, Parent_Parent_ID)
VALUES ('2', '1');
INSERT INTO Student_has_Parent (Student_Student_ID, Parent_Parent_ID)
VALUES ('2', '2');
INSERT INTO Student_has_Parent (Student_Student_ID, Parent_Parent_ID)
VALUES ('3', '3');
--Attendance
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Present', 'N/A', '1', '1');
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Present', 'N/A', '1', '2');
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Late', 'N/A', '1', '3');
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Absent', 'N/A', '2', '1');
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Present', 'N/A', '2', '2');
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Present', 'N/A', '2', '3');
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Present', 'N/A', '3', '1');
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Late', 'N/A', '3', '2');
INSERT INTO Attendance (Attendance_Status, Attendance_Remarks, Class_ID, Student_ID)
VALUES ('Absent', 'N/A', '3', '3');
---------------------------------------------------------------------------------------------------


------Useful Queries----------------------

-----GET CLASS INFORMATION----
SELECT
			 LOWER( Class.Class_Start_Timestamp ) 	                      AS 'Class Start Time',
			 LOWER( Class.Class_End_Timestamp ) 	                        AS 'Class End Time',
			 LOWER( Subject.Subject_Name ) 		                            AS 'Subject Name',
			 LOWER( Room.Room_Name ) 								 	                    AS 'Room Name',
       CONCAT( Teacher.Teacher_Fname, ' ' , Teacher.Teacher_Lname)  AS 'Teacher Name'

FROM Class, Subject, Room, Teacher

WHERE Class.Subject_ID = Subject.Subject_ID
		AND Class.Room_ID = Room.Room_ID
		AND Class.Teacher_ID = Teacher.Teacher_ID

LIMIT 0 , 10;




SELECT Class.Class_ID AS 'id', Subject.Subject_Name AS 'title', CONCAT( Class.Class_Date, ' ' , Class.Class_Start_Time) AS 'start', CONCAT( Class.Class_Date, ' ' , Class.Class_End_Time) AS 'end' FROM Student, Student_has_Class, Subject, Class, Room WHERE Student_has_Class.Student_ID = Student.Student_ID AND Student_has_Class.Class_ID = Class.Class_ID AND Class.Subject_ID = Subject.Subject_ID AND Class.Room_ID = Room.Room_ID AND Student.Student_ID LIKE 1;


-----GET ATTENDNACE INFORMATION-----
SELECT LOWER(  Attendance.Attendance_Status )AS 'Attendance_Info', COUNT(  Attendance.Attendance_Status) AS 'Attendance_Count' FROM Student, Attendance, Class, Subject WHERE Attendance.Class_ID = Class.Class_ID AND Attendance.Student_ID = Student.Student_ID AND Class.Subject_ID = Subject.Subject_ID AND LOWER( Student_Fname ) LIKE  'Nick' AND LOWER( Student_Lname ) LIKE 'Liffen' GROUP BY Attendance.Attendance_Status;

LIMIT 0 , 100;

-----GET STUDENT PARENT INFORMATION-----
SELECT CONCAT( Student.Student_Fname, ' ' , Student.Student_Lname)  AS 'Student_Name', Student.Student_Email, Student.Student_Year, Student.Student_Username FROM Parent, Student, Student_has_Parent WHERE Student_has_Parent.Student_Student_ID = Student.Student_ID AND Student_has_Parent.Parent_Parent_ID = Parent.Parent_ID AND LOWER( Parent_ID ) LIKE  '1'
-----GET Parent Student INFORMATION-----
SELECT CONCAT( Parent.Parent_Fname, ' ' , Parent.Parent_Lname)  AS 'Parent_Name', Parent.Parent_Email, Parent.Parent_Username FROM Parent, Student, Student_has_Parent WHERE Student_has_Parent.Student_Student_ID = Student.Student_ID AND Student_has_Parent.Parent_Parent_ID = Parent.Parent_ID AND LOWER( Parent_ID ) LIKE  '1'


SELECT LOWER(  Subject.Subject_Name ) AS 'Subject_Name', LOWER(  Attendance.Attendance_Status )AS 'Attendance_Info', COUNT(  Attendance.Attendance_Status) AS 'Attendance_Count' FROM Student, Attendance, Class, Subject WHERE Attendance.Class_ID = Class.Class_ID AND Attendance.Student_ID = Student.Student_ID AND Class.Subject_ID = Subject.Subject_ID AND LOWER( Student.Student_ID ) = '4' AND LOWER( Subject.Subject_ID ) = '1' GROUP BY Subject.Subject_Name, Attendance.Attendance_Status;



SELECT Student_ID, CONCAT( Student.Student_Fname, ' ' , Student.Student_Lname)  AS 'Student_Name', CONCAT( Parent.Parent_Fname, ' ' , Parent.Parent_Lname)  AS 'Parent_Name', Student_Email, Student_Year, Student_Username FROM Student, Parent, Student_has_Parent WHERE Student_has_Parent.Student_Student_ID = Student.Student_ID AND Student_has_Parent.Parent_Parent_ID = Parent.Parent_ID AND LOWER( Student_ID ) LIKE  '1'


------GET ALL THE TEACHERS CLASSES------
SELECT CONCAT( Teacher.Teacher_Fname, ' ' , Teacher.Teacher_Lname)    AS 'Teacher Name',
       LOWER(  Subject.Subject_Name ) 		                            AS 'Subject Name',
       LOWER(  Class.Class_Start_Time ) 	                            AS 'Class Start Time',
       LOWER(  Class.Class_End_Time ) 	                              AS 'Class End Time',
       LOWER(  Class.Class_Date ) 	                                  AS 'Class Date',
       LOWER(  Class.Class_Level ) 	                                  AS 'Class Level'

FROM Teacher, Subject, Class, Room

WHERE Class.Teacher_ID = Teacher.Teacher_ID
  AND Class.Subject_ID = Subject.Subject_ID
  AND Class.Room_ID = Room.Room_ID
  AND LOWER( Teacher.Teacher_ID ) LIKE  '3';



SELECT Class.Class_ID, Subject.Subject_Name, Class.Class_Start_Time, Class.Class_End_Time, Class.Class_Date, Class.Class_Level FROM Teacher, Subject, Class, Room WHERE Class.Teacher_ID = Teacher.Teacher_ID AND Class.Subject_ID = Subject.Subject_ID AND Class.Room_ID = Room.Room_ID AND Teacher.Teacher_ID LIKE  '3';




SELECT Class.Class_ID AS 'id', Subject.Subject_Name AS 'title', CONCAT( Class.Class_Date, ' ' , Class.Class_Start_Time) AS 'start', CONCAT( Class.Class_Date, ' ' , Class.Class_End_Time) AS 'end' FROM Teacher, Subject, Class, Room WHERE Class.Teacher_ID = Teacher.Teacher_ID AND Class.Subject_ID = Subject.Subject_ID AND Class.Room_ID = Room.Room_ID AND Teacher.Teacher_ID LIKE  '3';




--Get All Students in a class based on a Student ID
SELECT Student.Student_ID AS 'Student ID', Class.Class_ID AS 'Class ID', CONCAT( Class.Class_Date, ' ' , Class.Class_Start_Time) AS 'start', CONCAT( Class.Class_Date, ' ' , Class.Class_End_Time) AS 'end' FROM Student, Class, Student_Has_Class WHERE Student_Has_Class.Student_ID = Student.Student_ID AND Student_Has_Class.Class_ID = Class.Class_ID AND Student.Student_ID LIKE  '1';




SELECT Class.Class_Date, Class.Class_Start_Time, Class.Class_End_Time, Subject.Subject_Name, Room.Room_Name, Teacher.Teacher_Title, Teacher.Teacher_Fname, Teacher.Teacher_Lname FROM Class, Subject, Room, Teacher WHERE Class.Subject_ID = Subject.Subject_ID AND Class.Room_ID = Room.Room_ID AND Class.Teacher_ID = Teacher.Teacher_ID;






--Get all Classes Based on Teacher Information --
SELECT Class.Class_ID AS 'id', Subject.Subject_Name AS 'title', CONCAT( Class.Class_Date, ' ' , Class.Class_Start_Time) AS 'start', CONCAT( Class.Class_Date, ' ' , Class.Class_End_Time) AS 'end', Room.Room_Name AS 'room', CONCAT( Teacher.Teacher_Fname, ' ' , Teacher.Teacher_Lname) AS 'teacher' FROM Teacher, Subject, Class, Room WHERE Class.Teacher_ID = Teacher.Teacher_ID AND Class.Subject_ID = Subject.Subject_ID AND Class.Room_ID = Room.Room_ID AND Teacher.Teacher_ID LIKE ${userID}




----------------------------- RUN THIS QUERY AS A BUNCH

-- Run This Query to get the current Class ID and Student ID that the Student is supposed to be in--
SELECT Class.Class_ID AS 'Class_ID', Student.Student_ID AS 'Student_ID' FROM Student, Student_has_Class, Subject, Class, Room, Teacher WHERE Student_has_Class.Student_ID = Student.Student_ID AND Student_has_Class.Class_ID = Class.Class_ID AND Class.Subject_ID = Subject.Subject_ID AND Class.Teacher_ID = Teacher.Teacher_ID AND Class.Room_ID = Room.Room_ID AND NOW() BETWEEN Class.Class_Start_Timestamp AND Class.Class_End_Timestamp AND Student.Student_ID LIKE '1'

-- If the above query is empty then the student isn't supposed to be in a class?

-- If there is data then run the below query

--Gets Start & End Time for all classes and returns the attendnace status for each class. Based on a Student ID
SELECT Student.Student_ID AS 'Student ID', Class.Class_ID AS 'Class ID', Class.Class_Start_Timestamp AS 'start', Class.Class_End_Timestamp AS 'end', Subject.Subject_Name as 'Subject_Name', Attendance.Attendance_Status AS 'Attendance_Status' FROM Student, Class, Student_Has_Class, Subject, Attendance WHERE Student_Has_Class.Student_ID = Student.Student_ID AND Student_Has_Class.Class_ID = Class.Class_ID AND Class.Subject_ID = Subject.Subject_ID AND Attendance.Class_ID = Class.Class_ID AND Attendance.Student_ID = Student.Student_ID AND Class.Class_ID LIKE  '11' AND Student.Student_ID LIKE '1';

--Get the Attendance Remarks, if none then teachr hasn't taken class yet



--Gets Attendnace Information based on the last day, week or month. (Change variable at end). Need Student ID.
SELECT Class.Class_ID AS 'Class ID', Subject.Subject_Name as 'Subject_Name', Class.Class_Start_Timestamp AS 'start',  CONCAT( Teacher.Teacher_Fname, ' ' , Teacher.Teacher_Lname) AS 'Teacher_Name', Attendance.Attendance_Status AS 'Attendance_Status' FROM Student, Class, Student_Has_Class, Subject, Teacher, Attendance WHERE Student_Has_Class.Student_ID = Student.Student_ID AND Student_Has_Class.Class_ID = Class.Class_ID AND Class.Teacher_ID = Teacher.Teacher_ID AND Class.Subject_ID = Subject.Subject_ID AND Attendance.Class_ID = Class.Class_ID AND Attendance.Student_ID = Student.Student_ID AND Class.Class_Start_Timestamp > DATE_SUB(NOW(), INTERVAL 1 MONTH) AND Student.Student_ID LIKE '1' ORDER BY start ASC;


SELECT Class.Class_ID AS 'Class_ID',
          Student.Student_ID AS 'Student_ID',
          IFNULL(Attendance.Attendance_Status, 0) AS 'Attendance'

FROM Student, Student_has_Class, Subject, Class, Room, Teacher, Attendance

WHERE Student_has_Class.Student_ID = Student.Student_ID
  AND Student_has_Class.Class_ID = Class.Class_ID
    AND Class.Subject_ID = Subject.Subject_ID
      AND Attendance.Class_ID = Class.Class_ID
        AND Attendance.Student_ID = Student.Student_ID
          AND Class.Teacher_ID = Teacher.Teacher_ID
            AND Class.Room_ID = Room.Room_ID AND NOW() BETWEEN Class.Class_Start_Timestamp
              AND Class.Class_End_Timestamp AND Student.Student_ID LIKE '1';


SELECT Class.Class_ID AS 'Class_ID',
          Student.Student_ID AS 'Student_ID',
          IFNULL(Attendance.Attendance_Status, 0) AS 'Attendance'

FROM Class
  INNER JOIN Student
    ON Subject.Subject_ID=Class.Subject_ID
  INNER JOIN Student_has_Class
    ON Student.Student_ID=Student_has_Class.Student_ID AND Class.Class_ID=Student_has_Class.Class_ID
  INNER JOIN Attendance
    ON Class.Class_ID=Attendance.Class_ID;








SELECT Class.Class_ID AS 'Class_ID',
          Student.Student_ID AS 'Student_ID',
          Attendance.Attendance_Status AS 'Attendance'

FROM Student, Student_has_Class, Subject, Class, Attendance

WHERE Student_has_Class.Student_ID = Student.Student_ID
  AND Student_has_Class.Class_ID = Class.Class_ID
    AND Class.Subject_ID = Subject.Subject_ID
      AND Attendance.Class_ID = Class.Class_ID
        AND Attendance.Student_ID = Student.Student_ID
            AND NOW() BETWEEN Class.Class_Start_Timestamp AND Class.Class_End_Timestamp
              AND Student.Student_ID LIKE '1';


              SELECT  student.Student_ID as 'Student_ID',
                      case when class.class_id is null then 'No Class ATM' else class.class_id end as 'Class_ID',
                      case when Attendance.Attendance_Status is null then 'Not Present' else Attendance.Attendance_Status end as 'attendence_status'
              FROM Student
              LEFT OUTER JOIN Student_Has_Class ON(student_has_class.student_id = student.student_id
                                                    AND Student.student_id like '1')
              LEFT OUTER JOIN class ON(class.class_id = student_has_class.class_id)
              INNER JOIN Subject ON(class.subject_id = subject.subject_id)
              LEFT JOIN Attendance on(Attendance.class_id = class.class_ID
                                      AND Attendance.student_id = student.student_id)
              WHERE NOW() between class.class_start_timestamp and class.class_end_timestamp;




              SELECT  student.Student_ID as 'Student_ID',
                      case when class.class_id is null then 'No Class ATM' else class.class_id end as 'Class_ID',
                      case when Attendance.Attendance_Status is null then 'Not Present' else Attendance.Attendance_Status end as 'attendence_status'
              FROM Student
              INNER JOIN Student_Has_Class ON(student_has_class.student_id = student.student_id)
              INNER JOIN class ON(class.class_id = student_has_class.class_id)
              INNER JOIN Subject ON(class.subject_id = subject.subject_id)
              LEFT JOIN Attendance on(Attendance.class_id = class.class_ID
                                      AND Attendance.student_id = student.student_id)
              WHERE NOW() between class.class_start_timestamp and class.class_end_timestamp
              AND Student.student_id like '1'



                      --WORKING QUERY - NEEDS CHANGING THOUGH
                        SELECT DISTINCT student.Student_ID as 'Student_ID',
                                CONCAT( Student.Student_Fname, ' ' , Student.Student_Lname)  AS 'Student_Name',
                                 Student.Student_Email AS 'Student_Email',
                                 Student.Student_Year AS 'Student_Year',
                                 Student.Student_Username AS 'Student_Username',
                                 CONCAT ((CASE when Subject.Subject_Name is null then 'No Class ATM' else Subject.Subject_Name end), ' ',  (CASE when Attendance.Attendance_Status is null then 'No attendance taken' else Attendance.Attendance_Status end)) AS 'Attendance_Info'
                        FROM Student
                          LEFT JOIN Student_Has_Class ON(student_has_class.student_id = student.student_id)
                          LEFT JOIN class ON class.class_id = student_has_class.class_id
                              AND NOW() between class.class_start_timestamp and class.class_end_timestamp
                          LEFT JOIN Subject ON(class.subject_id = subject.subject_id)
                          LEFT JOIN Attendance on(Attendance.class_id = class.class_ID
                              AND Attendance.student_id = student.student_id)
                        WHERE Student.student_id = 4
                          ORDER BY class.class_id DESC
                            LIMIT 1;

                            CONCAT (Subject.Subject_Name AS 'Subject_Name', ' ',  CASE when Attendance.Attendance_Status is null then 'No attendance taken' else Attendance.Attendance_Status end as 'Attendance_Status')

                                    SELECT  DISTINCT student.Student_ID as 'Student_ID',
                                    IFNULL (class.class_id, 0) as 'Class_ID',
                                    IFNULL (Attendance.Attendance_Status, 0) as 'Class_ID'
                                    FROM Student
                                      LEFT JOIN Student_Has_Class ON(student_has_class.student_id = student.student_id)
                                        LEFT JOIN class ON class.class_id = student_has_class.class_id
                                            AND NOW() between class.class_start_timestamp and class.class_end_timestamp
                                          LEFT JOIN Subject ON(class.subject_id = subject.subject_id)
                                            LEFT JOIN Attendance on(Attendance.class_id = class.class_ID
                                              AND Attendance.student_id = student.student_id)
                                                WHERE Student.student_id = 1;





/*
              SELECT class.class_id as 'Class_ID',
                      student.Student_ID as 'Student_ID',
                      case when attendence.attendence_status is null then 'Not Present' else attendence.attendence_status end as 'attendence_status'
              FROM Student
              INNER JOIN Student_Has_Class ON(student_has_class.student_id = student.student_id)
              INNER JOIN class ON(class.class_id = student_has_class.class_id)
              INNER JOIN Subject ON(class.subject_id = subject.subject_id)
              LEFT JOIN Attendence on(attendence.class_id = class.class_ID
                                      AND attendence.student_id = student.student_id)
              WHERE NOW() between class.class_start_timestamp and class.class_end_timestamp
              AND Student.student_id like '1'
*/


--WORKING QUERY - NEEDS CHANGING THOUGH
  SELECT DISTINCT student.Student_ID as 'Student_ID',
    CONCAT( Student.Student_Fname, ' ' , Student.Student_Lname)  AS 'Student_Name',
      Student.Student_Email AS 'Student_Email', Student.Student_Year AS 'Student_Year',
        Student.Student_Username AS 'Student_Username',
          CASE when Subject.Subject_Name is null then 'Student Has No Class' else Subject.Subject_Name end as 'Subject_Name',
            CASE when Attendance.Attendance_Status is null then 'No Attendance Taken Yet' else Attendance.Attendance_Status end as 'Attendance_Status'
  FROM Student
    LEFT JOIN Student_Has_Class ON(student_has_class.student_id = student.student_id)
      LEFT JOIN class ON class.class_id = student_has_class.class_id
        AND NOW() between class.class_start_timestamp AND class.class_end_timestamp
    LEFT JOIN Subject ON(class.subject_id = subject.subject_id)
    LEFT JOIN Attendance ON(Attendance.class_id = class.class_ID
        AND Attendance.student_id = student.student_id)
    WHERE Student.student_id = 1;
      ORDER BY class.class_id
    DESC LIMIT 1


    SELECT DISTINCT student.Student_ID as 'Student_ID', CONCAT( Student.Student_Fname, ' ' , Student.Student_Lname)  AS 'Student_Name', Student.Student_Email AS 'Student_Email', Student.Student_Year AS 'Student_Year', Student.Student_Username AS 'Student_Username', CASE when Subject.Subject_Name is null then 'Student Has No Class' else Subject.Subject_Name end as 'Subject_Name', CASE when Attendance.Attendance_Status is null then 'No Attendance Taken Yet' else Attendance.Attendance_Status end as 'Attendance_Status' FROM Student LEFT JOIN Student_Has_Class ON(student_has_class.student_id = student.student_id) LEFT JOIN class ON class.class_id = student_has_class.class_id AND NOW() between class.class_start_timestamp AND class.class_end_timestamp LEFT JOIN Subject ON(class.subject_id = subject.subject_id) LEFT JOIN Attendance ON(Attendance.class_id = class.class_ID AND Attendance.student_id = student.student_id) LEFT JOIN Student_has_Parent ON (Student_has_Parent.Student_Student_ID = Student.Student_ID) LEFT JOIN Parent ON (Parent.Parent_ID = Student_has_Parent.Parent_Parent_ID) WHERE Parent.Parent_ID = '${parentID}' ORDER BY class.class_id DESC LIMIT 2;
